create project, add createAccountTest, signInTest
Anastasiyyya/StoreAutomation pull request #1
Opened 2021-08-07 17:48 UTC by Anastasiyyya

2021-08-08 19:14 UTC, vchesnakou requested changes
please make fixes

2021-08-08 19:14 UTC, vchesnakou commented on pom.xml
> +        <maven-surefire-plugin.version>3.0.0-M4</maven-surefire-plugin.version>
эта проперти где-нибудь используется ? наверное её надо юзать в строке 24

2021-08-08 19:14 UTC, vchesnakou commented on pom.xml
> +                        <version>1.9.6</version>
эту версию давай тоже в properties вынесем

2021-08-08 19:14 UTC, vchesnakou commented on pom.xml
> +                <version>2.10.0</version>
эту тоже

2021-08-08 19:14 UTC, vchesnakou commented on pom.xml
> +            <version>2.13.9</version>
эту тоже

2021-08-08 19:14 UTC, vchesnakou commented on src/main/java/pageConstants/IConstants.java
> +package pageConstants;
названия пакетов пишутся в snake_case, т.е у тебя должно быть page_constants либо лучше назвать url_costants

2021-08-08 19:14 UTC, vchesnakou commented on src/main/java/pageElements/Button.java
> +package pageElements;
также поправь название (проверь остальные пакеты тоже )

2021-08-08 19:14 UTC, vchesnakou commented on src/main/java/pages/CreateAccountPage.java
> +        new Input("Mobile phone").enterTextToField(account.getMobilePhone());
на будущее: все эти "First name", "Last name" и тд можно тоже в константы выносить

2021-08-08 19:14 UTC, vchesnakou commented on src/test/java/testData/IGenerateEmail.java
> +public interface IGenerateEmail {
не совсем понимаю, почему это интерфейс, скорее просто утилитный класс. Также советую переименовать в Utils например. Также метод generateRandomString можно сделать public static и потом вызывать его в любом месте через Utils.generateRandomString (без new )

2021-08-09 16:23 UTC, Anastasiyyya commented on src/test/java/testData/IGenerateEmail.java
> +public interface IGenerateEmail {
исправлено

2021-08-10 10:46 UTC, vchesnakou approved these changes
please merge

2021-08-11 16:36 UTC, merged