added tests covering add/delete product to/from cart
Anastasiyyya/StoreAutomation pull request #2
Opened 2021-08-11 19:31 UTC by Anastasiyyya

2021-08-12 15:32 UTC, vchesnakou requested changes
please make fixes and send to review

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/page_elements/Button.java
> +        $(button).click();
а мы не можем найти общий локатор для всех кнопок на сайте и объявить его в этом же классе ?

сделать по принципу: 
   ```
 public static final String BUTTON_XPATH = "...........//*[contains(text(),'%s')]";

    public Button(String label) {
        this.label = label;
    }

    public void click() {
        log.info(String.format("Click button '%s'.", label));
        String.format(BUTTON_XPATH, label)).click();
    }
```

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/page_elements/Dropdown.java
> +        }else {
добавь пробел перед else

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/CartPage.java
> +    public static final String DELETE_PRODUCT_BUTTON_XPATH = "//*[contains(text(),'%s')]/ancestor::*[@id = 'product_11_0_0_0']//*[@class = 'cart_quantity_delete']";
а что за [@id = 'product_11_0_0_0'] ? выглядит странным

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/CartPage.java
> +        //Selenide.Wait().withTimeout(Duration.ofSeconds(5));
тут нужен этот код ?

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/CartPage.java
> +        Selenide.sleep(3000);
почему sleep?

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/page_elements/Dropdown.java
> +    public static final String BIRTHDAY_DAY_MONTH_DROPDOWN_CSS = "[name='%s']"; //days //months
//days //months - можно не перечислять

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/HeaderPage.java
> +    public static final String BLOCK_SUB_MENU_CSS = ".submenu-container ul [title='%s']"; //T-shirts //Blouses //Casual Dresses //Evening Dresses //Summer Dresses
//T-shirts //Blouses //Casual Dresses //Evening Dresses //Summer Dresses - тоже можно не перечислять. т.к. если что-то из этих опций на сайте будет меняться, эти уже будут не валидными и прийдется эти комменты тоже править

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/HeaderPage.java
> +        actions().moveToElement($(String.format(BLOCK_TOP_MENU_CSS, buttonName))).perform();
для actions().moveToElement можно создать отдельный метод в BasePage, moveTolElement(String locator)

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/HeaderPage.java
> +        actions().moveToElement($(String.format(BLOCK_SUB_MENU_CSS, buttonName))).click().perform();
тут тогда будешь использовать общий метод

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/ProductCategoryPage.java
> +    public static final String PRODUCT_NAME_XPATH = "//*[contains(text(),'%s')]/ancestor::*[@id='product_11_0_0_0']//p/a";
[@id='product_11_0_0_0'] тоде выглядит странно

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/ProductCategoryPage.java
> +    public ProductCategoryPage chooseDropdownAndOption(String dropdownName, String option) {
chooseOptionFromDropdown

2021-08-12 15:32 UTC, vchesnakou commented on src/main/java/pages/ProductCategoryPage.java
> +    public ProductCategoryPage changeViewTo(String view) {
changeProductsViewTo

2021-08-12 15:32 UTC, vchesnakou commented on src/test/java/tests/AddProductsToCartTests.java
> +                .selectProductByPrice("$27.43")
для этих значений тоже лучше будет завести константы в ITestConstants

2021-08-12 15:32 UTC, vchesnakou commented on src/test/java/tests/AddProductsToCartTests.java
> +        Assert.assertEquals(productCategoryPage.getProductNameByPrice("27.43"), cartPage.getProductName("Printed Maxi Dress"));
ты сравниваешь UI с UI , в expected result у тебя должно быть просто "Printed Maxi Dress"

2021-08-12 15:32 UTC, vchesnakou commented on src/test/java/tests/CreateNewAccountTest.java
> +        Assert.assertEquals(myAccountPage.getText(CREATED_ACCOUNT_MESSAGE_CSS),"Welcome to your account. Here you can manage all of your personal information and orders.");
CREATED_ACCOUNT_MESSAGE_CSS - локаторы не должны быть в тестах. Они должны быть только на страницах

2021-08-12 15:32 UTC, vchesnakou commented on src/test/java/tests/DeleteProductFromCartTest.java
> +                .findProductByNameAndDelete("Printed Maxi Dress");
для всех этих действий потом лучше будет создать steps

2021-08-12 15:32 UTC, vchesnakou commented on src/test/java/tests/SignInTests.java
> +        Assert.assertEquals(myAccountPage.getText(CREATED_ACCOUNT_MESSAGE_CSS),"Welcome to your account. " +
CREATED_ACCOUNT_MESSAGE_CSS - также тут не должно быть локатора

2021-08-16 17:17 UTC, Anastasiyyya commented on src/main/java/pages/CartPage.java
> +    public static final String DELETE_PRODUCT_BUTTON_XPATH = "//*[contains(text(),'%s')]/ancestor::*[@id = 'product_11_0_0_0']//*[@class = 'cart_quantity_delete']";
исправлено

2021-08-16 17:18 UTC, Anastasiyyya commented on src/main/java/pages/CartPage.java
> +        //Selenide.Wait().withTimeout(Duration.ofSeconds(5));
не нужен, удалила

2021-08-16 17:30 UTC, Anastasiyyya commented on src/test/java/tests/AddProductsToCartTests.java
> +        Assert.assertEquals(productCategoryPage.getProductNameByPrice("27.43"), cartPage.getProductName("Printed Maxi Dress"));
исправлено

2021-08-16 17:34 UTC, Anastasiyyya commented on src/test/java/tests/SignInTests.java
> +        Assert.assertEquals(myAccountPage.getText(CREATED_ACCOUNT_MESSAGE_CSS),"Welcome to your account. " +
исправлено

2021-08-16 17:35 UTC, Anastasiyyya commented on src/test/java/tests/CreateNewAccountTest.java
> +        Assert.assertEquals(myAccountPage.getText(CREATED_ACCOUNT_MESSAGE_CSS),"Welcome to your account. Here you can manage all of your personal information and orders.");
исправлено

2021-08-16 17:54 UTC, Anastasiyyya commented on src/test/java/tests/AddProductsToCartTests.java
> +                .selectProductByPrice("$27.43")
исправлено во всех тестах

2021-08-17 18:14 UTC, merged