added 2 tests SearchProduct
Anastasiyyya/StoreAutomation pull request #3
Opened 2021-08-17 19:23 UTC by Anastasiyyya

2021-08-18 20:10 UTC, vchesnakou requested changes
please make fixes

2021-08-18 20:10 UTC, vchesnakou commented on src/main/java/page_objects/Account.java
> +    }
на будущее: можем подключить Lombok и повесить аннотацию @AllArgsConstructor, тогда можно будет не писать эти конструкторы руками

2021-08-18 20:10 UTC, vchesnakou commented on src/main/java/pages/PersonalInfoPage.java
> +        new Input("First name").replaceFieldTextTo(account.getFirstName() + "UPDATE");
для "UPDATE" можно будет тоже завести константу

2021-08-18 20:10 UTC, vchesnakou commented on src/main/java/pages/PersonalInfoPage.java
> +    }*/
удаляй, если код не нужен, либо комменты оставляй (TODO:..)

2021-08-18 20:10 UTC, vchesnakou commented on src/test/java/tests/ChangePersonalInfoTest.java
> +        //Assert.assertEquals(personalInfoPage.getChangedMessageText(), "Your personal information has been successfully updated.");
почему ассерт закоменчен ?

2021-08-19 04:52 UTC, Anastasiyyya commented on src/main/java/page_objects/Account.java
> +    }
уже, в след ПР))

2021-08-19 04:53 UTC, Anastasiyyya commented on src/main/java/pages/PersonalInfoPage.java
> +        new Input("First name").replaceFieldTextTo(account.getFirstName() + "UPDATE");
этот метод удален как нерабочий, на сайте баг и кнопка save не нажимается

2021-08-19 04:53 UTC, Anastasiyyya commented on src/main/java/pages/PersonalInfoPage.java
> +    }*/
удалена вся страница

2021-08-19 04:53 UTC, Anastasiyyya commented on src/test/java/tests/ChangePersonalInfoTest.java
> +        //Assert.assertEquals(personalInfoPage.getChangedMessageText(), "Your personal information has been successfully updated.");
потому что метод нерабочий)

2021-08-19 17:42 UTC, closed without merging